version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 8876:80
    depends_on:
      - app
    container_name: thedoctor_nginx
    
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on: 
      - db
    container_name: thedoctor_app

  db:
    image: mysql:8.0
    dns:
      - 8.8.8.8
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: thedoctor
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: --lower_case_table_names=0
    container_name: thedoctor_db